Update
grammyjs/link-checker pull request #13
Opened 2023-12-13 04:36 UTC by quadratz

- update dependencies
- fix error: maximum limit of redirects
- add timeout and delay

https://github.com/grammyjs/website/pull/961#issuecomment-1851625755

2024-01-18 04:04 UTC, dcdunkan requested changes
Hi, thank you for spending your time on this. And sorry about the late review. The implementation generally looks good. But I have left some suggestions. Need your opinion as well. Thanks again.

2024-01-18 04:04 UTC, dcdunkan commented on fetch.ts
> +        retryDelay = Math.min(retryDelay * 2, maxDelay);
I understand that having a small delay is good before retrying. But, I don't see how it is really useful to wait twice the delay of the previous retry. 2, 4, 8, 16, 30. That is just a waste of time I guess. I know currently the link checker doesn't even have timeouts and I agree that it is even worse. But since we're improving that, I don't think we really need this kind of waiting. Please let me know if there is an actual use case, other than hoping that waiting with even longer delays each time, might make the website respond as expected. If that's the case, we can maybe consider increasing the delay a little bit rather than waiting twice longer on each retry.

2024-01-18 04:04 UTC, dcdunkan commented on fetch.ts
> +    } while (retries <= maxRetries && response == null);
```suggestion
    } while (retries < maxRetries && response == null);
```

~~`<=` makes 6 retries in total, ignoring `maxRetries` (= 5), because `retries` starts from `0`~~. My mistake.

2024-01-18 04:04 UTC, dcdunkan commented on fetch.ts
> +        const controller = new AbortController();
I think since our only goal here is to just timeout the request, we can replace `AbortController` with `AbortSignal` and get rid of the `[set,clear]Timeout`s, and make this simpler.

```ts
const timeoutSignal = AbortSignal.timeout(retryDelay);
await fetch(url, { ...options, redirect: "manual", signal: timeoutSignal })
```

2024-01-18 04:04 UTC, dcdunkan commented on fetch.ts
> +        if (err.name === "AbortError") {
Need to be changed to `TimeoutError` if we're changing to `AbortSignal.timeout`.

2024-01-18 04:04 UTC, dcdunkan commented on utilities.ts
> +  if (response.isRedirected && !isValidRedirection(new URL(transformed), new URL(response.url))) {
There's a catch. You set `isRedirected` to `true` in manual redirections. But in the `response` of manual redirections, the `url` property won't be the redirected URL. It'll be the same URL as we requested, and that is by design.

We could
1. either extend the response by adding one more property, perhaps `redirectedUrl`, and assign the value of `Location` header (if it exists, otherwise the requested URL) in the response. This gives us an opportunity to make sure that it redirects to an expected page even when redirect is set to `"manual"`,
2. or we could just check if the URL exists in `MANUAL_REDIRECTIONS` here as well. If it is, we should ignore.

I'd go with 1 for now, and if gets too complicated to manage these redirects sometime in the future, we can switch to 2.

2024-01-18 04:04 UTC, dcdunkan commented on group_links.ts
>  import { yellow } from "./deps/std/fmt.ts";
```suggestion
import { DOMParser } from "./deps/deno_dom.ts";
import { blue, yellow } from "./deps/std/fmt.ts";
```

That'd be better. Sorry, I missed this import before.

2024-01-18 04:04 UTC, dcdunkan commented on fetch.ts
> +        (to.hostname === "accounts.google.com" && (segments.to[2] === "signin" || segments.to[1] === "signup")) || // Google
We seems to get different paths from that redirect.

> The redirect in my browser is https://accounts.google.com/signup/v2/createaccount?theme=glif&flowName=GlifWebSignIn&flowEntry=SignUp.

> Mine actually is https://accounts.google.com/lifecycle/steps/signup/name with some long query parameters added to that.

Whatever the path is, it seems to have the "signin" or "signup" somewhere, not necessarily at the beginning. So, I think a simple `.includes` check would do.

```suggestion
        (to.hostname === "accounts.google.com" && (segments.to.includes("signin") || segments.to.includes("signup"))) || // Google
```

2024-02-02 21:07 UTC, dcdunkan commented
@quadratz I have made the changes and will be merging this now. Thanks again for the contribution!

2024-02-02 21:07 UTC, merged

2024-02-12 16:50 UTC, quadratz reviewed
LGTM. (Sorry for the late reply) >_<